version: '3'
services:
    web:
        build: .
        ports:
            - "8000:8000"
            - "8080:8080"
        environment:
            PORT: "8000"
            DATABASE_URL: "postgres://tsurezure:tsurezure@db:5432/tsurezure"
            ADMIN_USER: "osak"
            ADMIN_PASS: "azusa"
        depends_on:
            - "db"
    db:
        image: "postgres:12-alpine"
        ports:
            - "15432:5432"
        environment:
            POSTGRES_USER: "tsurezure"
            POSTGRES_PASSWORD: "tsurezure"
            POSTGRES_DB: "tsurezure"
        volumes:
            - "db:/var/lib/postgresql/data"
volumes:
    db:
