version: '3'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        environment:
            ROCKET_ADDRESS: "0.0.0.0"
        depends_on:
            - "db"
    db:
        image: "postgres:12-alpine"
        ports:
            - "15432:5432"
        environment:
            POSTGRES_USER: "tsurezure"
            POSTGRES_PASSWORD: "tsurezure"
            POSTGRES_DB: "tsurezure"
        volumes:
            - "db:/var/lib/postgresql/data"
volumes:
    db:
